# Generated by Django 5.2.3 on 2025-11-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='destination_lat',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination_lon',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='origin_lat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='origin_lon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
