# Generated by Django 5.2.3 on 2025-11-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_trip_destination_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
