# Generated by Django 5.2.7 on 2025-10-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UI', '0003_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='order',
            field=models.PositiveIntegerField(blank=True, help_text='Used to order steps in the timeline', null=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
